spring:
  application:
    name: notification-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5434/notificationdb
    username: notificationuser
    password: notificationpass

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5434/notificationdb
    user: notificationuser
    password: notificationpass
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ecouser
    password: ecopass

server:
  port: 8080

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

logging:
  level:
    com.unimag.trip_service: DEBUG
    org.springframework.web: INFO
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true