spring.application.name=notification-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/notification_db
spring.datasource.username=admin
spring.datasource.password=teaminsulina
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=ecouser
spring.rabbitmq.password=ecopass

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=conectaciudadxyz@gmail.com
spring.mail.password=ekimcelhwyrkctym
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
